/**
 * CGE Web Loader
 * Generated by CGE
 */

// Asset preloading configuration
var CGE_PRELOAD_ASSETS = [
    "assets/data.json"
];

// Global error handler
window.onerror = function(message, source, line, col, error) {
    console.error('CGE Error:', message, 'at', source, ':', line);
    var loading = document.getElementById('loading');
    if (loading) {
        loading.innerHTML = '<div style="color: red;">Error: ' + message + '</div>';
    }
    return true;
};

// Wait for module to be ready
function waitForModule(callback) {
    if (typeof Module !== 'undefined' && Module.calledRun) {
        callback();
    } else {
        setTimeout(function() { waitForModule(callback); }, 100);
    }
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', function() {
    console.log('CGE: Initializing SunderReach...');
});
